#
#spring:server:
#  #  port: 8686
spring:
  profiles:
    active: dev
#  freemarker:
#    suffix: .ftl
#    content-type: text/html
#    charset: UTF-8
#    template-loader-path: classpath:/views/
  thymeleaf:
    prefix: classpath:/html/
    cache: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger-%msg%n"
    level: debug
  file:
    path: "."
    name: "springboot.log"